#pragma once
void test5_1();
void test5_2();
void test5_3();
void test5_4();
void test5_5();
void test5_6();
void test5_7();
void test5_8();
void test5_9();
void test5_10();

void printInfo();
void test6_1();
void test6_2();
void test6_3();
void test6_4();
void test6_5();
void test6_6();
void test6_7();
void test6_8();
void test6_9();
void test6_10();

void test7_1();
double getAvg(double, double);
void test7_2();
float* inputArr();
void showArr(float arr[]);
float getAvgOfArr(float arr[]);
void test7_3();
struct box;
void showBox(struct box b);
void setBox(struct box *b);
void test7_4();
long double prbability(unsigned numbers, unsigned picks);
void test7_5();
long foo(long n);
void test7_6();
int Fill_array(double arr[], int len);
void Show_array(double arr[], int len);
void Reverse_Array(double arr[], int len);
void test7_7();
int fill_array(double ar[], int limit);
void show_array(const double ar[], int n);
void revalue(double r, double ar[], int n);
void test7_8();
void test7_9();
struct student;
int getInfo(student pa[], int n);
void display1(student st);
void display2(const student * ps);
void test7_10();